### ISSUE TITLE
Copy Relative Path not needed after VScode 1.26.0 update

### ISSUE THREAD

**Issue by ferry77** [sdras/vue-vscode-extensionpack#3]
Hi @sdras ,
I think after VSCode 1.26 we do not need Copy Relative Path extension anymore in your extensionpack since it has been built in?

Thanks,
Ferry

**Comment by sagirk** [comment]
Came here to report the same. Thanks for opening this @ferry77.

@sdras I'm unable to uninstall the Copy Relative Path extension separately as this extension pack depends on it. Since VSCode has absorbed this as a [built-in](https://code.visualstudio.com/updates/v1_26#_copy-relative-path) feature now, can we drop the dependency on the CRP extension?
